# Generated by Django 4.1 on 2023-11-28 03:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tiendaApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del departamento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('numProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('cantidad', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad del Producto')),
                ('cantidadMinima', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad Minima del Producto')),
                ('precio', models.PositiveBigIntegerField(default=1, verbose_name='Precio del Producto')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción del Producto')),
                ('foto', models.ImageField(default='productos/producto.jpg', null=True, upload_to=tiendaApp.models.Producto.generarNombre)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='rProducto',
            fields=[
                ('numProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('cantidad', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad del Producto')),
                ('cantidadMinima', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad Minima del Producto')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción del Producto')),
                ('foto', models.ImageField(default='productos/producto.jpg', null=True, upload_to=tiendaApp.models.rProducto.rgenerarNombre)),
            ],
            options={
                'verbose_name': 'rProducto',
                'verbose_name_plural': 'rProductos',
                'db_table': 'rproducto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='Run')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('sexo', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otros')], default='o', max_length=1)),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('contras', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('repcontras', models.CharField(max_length=50, verbose_name='Repetir Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['run', 'nombres', 'apellidos', 'sexo', 'fechaNac', 'email', 'contras', 'repcontras'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otros')], default='o', max_length=1)),
                ('codigoEmpleado', models.CharField(max_length=20, verbose_name='Código de Empleado')),
                ('sueldo', models.PositiveIntegerField(default=450000, verbose_name='sueldo Base')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tiendaApp.cargo')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
    ]
